Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    
    path('user/', include('User_auth.urls')),
    path('', include('main.urls')),
    path('cadmin/', include('adminside.urls')),
    path('products/', include('products.urls')),
    path('cart/',include('cart.urls')),
    path('user_profile/',include('user_profile.urls')),
    path('checkout/',include('orders.urls')),
    path('coupons/',include('coupons.urls')),
    path('offers/',include('offers.urls')),
    
    

   
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import include, path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:id>/", views.add_cart, name="add_cart"),
    path("remove_cart/<int:id>/", views.remove_cart, name="remove_cart"),
    path("delete_cart_item/<int:id>/", views.delete_cart_item, name="delete_cart_item"),
    path("update_cart/", views.update_cart, name="update_cart"),
]

main/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    path("shop/", views.shop, name="shop"),
    path("details/<int:id>/", views.product_details, name="product_details"),
    path("faq/", views.faq, name="faq"),
    path("contact/", views.contact, name="contact"),
]

orders/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.checkout ,name="checkout"),
    path('place_order/', views.place_order ,name="place_order"),
    path('coupon-applied/', views.apply_coupon ,name="apply_coupon"),
    path('list_order/', views.list_order ,name="list_orders"),
    path('change-status/<int:id>/', views.change_status ,name="change_status"),
    path('view-order/<int:id>/', views.view_order, name="view_order"),
    path('remove/<int:id>/', views.soft_remove, name="soft_remove"),
    path('delete/<int:id>/', views.order_delete, name="order_delete"),
    path('place-order/', views.place_order,name="online_payment"),
    path('online-payment/', views.online_payment ,name="online_payment_sucsses"),
    path('order-succssesfull/', views.order_sucsses ,name="order_sucsses"),
    path('submit-review/<int:id>/', views.submit_review ,name="submit_review"),
    

    

    
    
]

user_profile/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "user_profile"

urlpatterns = [
    path("profile/", views.profile, name="profile"),
    path("update-profile/", views.update_profile, name="update_profile"),
    path("address/", views.address, name="address"),
    path("add-address/", views.add_address, name="add_address"),
    path("delete_address/<int:id>/", views.delete_address, name="delete_address"),
    path("update_address/<int:id>/", views.update_address, name="update_address"),
    path("order-track/", views.order_track, name="order-track"),
    path(
        "cancel-product/<int:id>/<int:oid>/",
        views.cancel_product,
        name="cancel_product",
    ),
    path("cancel-order/<int:id>/", views.cancel_order, name="cancel_order"),
    path("remove-order/<int:id>/", views.remove_order, name="remove_order"),
    path("rewards/", views.rewards, name="rewards"),
    path("wallet/", views.wallet, name="wallet"),
    path("return-page/<int:id>/", views.return_page, name="return_page"),
    path("return-order/<int:id>/", views.return_order, name="return_order"),
    path("return-orders/", views.returnorder_page, name="returned_page"),
    path("view-returns/<int:id>/", views.view_returns, name="view_returns"),
    path("approve-return/<int:id>/", views.approve_return, name="approve_return"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("add-to-wishlist/<int:id>/", views.add_wishlist, name="add_wishlist"),
    path("remove-wishlist/<int:id>/", views.remove_wishlist, name="remove_wishlist"),
]

orders/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from .models import *

class FormWithCaptcha(forms.Form):
    captcha = ReCaptchaField()



class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['review','rating']

        

orders/views.py
import datetime
import json

from cart.models import *
from cart.views import _cart_id
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import never_cache
from user_profile.models import *

from .forms import FormWithCaptcha
from .models import *
from .forms import *


# Create your views here.
@never_cache
@login_required(login_url="userauth:login")
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        address = Address.objects.filter(user=request.user)
        profile = User_profile.objects.get(user=request.user)
    except:
        address = None
        profile = None
        messages.warning(request, 'Please complete your profile to proceed.')
        return redirect('user_profile:profile')

    cart_item = Cartitem.objects.filter(user=request.user)
    all_cart_item = not any(item.product.stock <= 0 for item in cart_item)

    if not all_cart_item:
        messages.error(request, 'One of the selected items is out of stock.')
        return redirect("cart:cart")

    try:
        tax = 0
        grand_total = 0
        shipping = 0

        cart_items = Cartitem.objects.filter(user=request.user, is_active=True)

        if not cart_items.exists():
            return redirect("main:shop")

        for cart_item in cart_items:
            product_price = cart_item.product.price
            product_offer = cart_item.product.offer
            category_offer = cart_item.product.category.offer
            
            if product_offer is None and category_offer is None:
                total += product_price * cart_item.quantity
                quantity += cart_item.quantity
            else:
                if product_offer and category_offer:
                    discount = max(product_offer.discount, category_offer.discount)
                elif product_offer:
                    discount = product_offer.discount
                else:
                    discount = category_offer.discount
                
                discount_price = (discount / 100) * float(product_price)
                discount_amount = float(product_price) - discount_price
                total += discount_amount * cart_item.quantity
                quantity += cart_item.quantity

        tax = (2 * total) / 100
        shipping = 20
        grand_total = total + shipping + tax

    except ObjectDoesNotExist:
        pass

    context = {
        "total": total,
        "quantity": quantity,
        "cart_items": cart_items,
        "captcha": FormWithCaptcha,
        "tax": tax,
        "shipping": shipping,
        "grandtotal": grand_total,
        "address": address,
        "profile": profile,
    }

    return render(request, "order/checkout.html", context)


@never_cache
@login_required(login_url="userauth:login")
def place_order(request, total=0, quantity=0):
    try:
        current_user = request.user
        cart_items = Cartitem.objects.filter(user=current_user)
        cart_count = cart_items.count()

        if request.method == "POST":
            selected_address_id = request.POST.get("address")
            payment_method = request.POST.get("pay-method")
            captcha = request.POST.get("g-recaptcha-response")

            if not selected_address_id:
                messages.error(request,"Please add an address from your profile to proceed")
                return redirect("orders:checkout")

            if not captcha:
                messages.error(request, "Confirm you are not a Robot")
                return redirect("orders:checkout")

            if payment_method == "COD":
                selected_address = get_object_or_404(
                    Address, id=selected_address_id, user=current_user
                )
                profile = User_profile.objects.get(user=current_user)

                tax = 0
                grand_total = 0
                shipping = 20  # Fixed shipping cost

                for cart_item in cart_items:
                    product_price = cart_item.product.price
                    product_offer = cart_item.product.offer
                    category_offer = cart_item.product.category.offer
                    
                    if product_offer is  None and category_offer is None:
                        total += cart_item.product.price * cart_item.quantity
                        quantity += cart_item.quantity
                    else:
                        if product_offer and category_offer:
                            discount = max(product_offer.discount,category_offer.discount)
                        elif product_offer:
                            discount = product_offer.discount
                        else:
                            discount = category_offer.discount
                        discount_price = (discount / 100) * float(product_price)
                        discount_amount = float(product_price) - discount_price
                        total += discount_amount * cart_item.quantity
                        quantity += cart_item.quantity

                tax = (2 * total) / 100
                grand_total = total + shipping + tax

                if 'disc_total' in request.session:
                    grand_total = request.session['disc_total']
                    del request.session['disc_total']

                data = Order(
                    user=current_user,
                    payment=payment_method,
                    first_name=profile.first_name,
                    last_name=profile.last_name,
                    phone=profile.mobile_number,
                    phone2=selected_address.phone,
                    email=profile.user.email,
                    address_line_1=selected_address.address,
                    state=profile.state,
                    district=selected_address.district,
                    zipcode=selected_address.zipcode,
                    hometown=selected_address.hometown,
                    order_total=grand_total,
                    tax=tax,
                    ip=request.META.get("REMOTE_ADDR"),
                    is_ordered=True,
                )

                data.save()

                if payment_method == "COD":
                    data.payment_status = "Pending"

                yr = int(datetime.date.today().strftime("%Y"))
                dt = int(datetime.date.today().strftime("%d"))
                mt = int(datetime.date.today().strftime("%m"))
                d = datetime.date(yr, mt, dt)
                current_date = d.strftime("%Y%m%d")
                order_number = current_date + str(data.id)
                data.order_number = order_number
                data.save()

                cart_items = Cartitem.objects.filter(user=request.user)
                for item in cart_items:
                    orderproduct = OrderProduct(
                        order=data,
                        payment=payment_method,
                        user=request.user,
                        product=item.product,
                        quantity=item.quantity,
                        product_price=item.product.price,
                        ordered=True,
                    )

                    orderproduct.save()

                    product = item.product
                    product.stock -= item.quantity
                    product.save()

                Cartitem.objects.filter(user=request.user).delete()

                if cart_count <= 0:
                    print(cart_count)
                    return redirect("main:shop")

                return render(request, "order/thankyou.html")
            
            elif payment_method == 'wallet':
                wallet = Wallet.objects.get(user=current_user)
                selected_address = get_object_or_404(
                    Address, id=selected_address_id, user=current_user
                )
                profile = User_profile.objects.get(user=current_user)

                tax = 0
                grand_total = 0
                shipping = 20  # Fixed shipping cost

                for cart_item in cart_items:
                    product_price = cart_item.product.price
                    product_offer = cart_item.product.offer
                    category_offer = cart_item.product.category.offer
                    
                    if product_offer is  None and category_offer is None:
                        total += cart_item.product.price * cart_item.quantity
                        quantity += cart_item.quantity
                    else:
                        if product_offer and category_offer:
                            discount = max(product_offer.discount,category_offer.discount)
                        elif product_offer:
                            discount = product_offer.discount
                        else:
                            discount = category_offer.discount
                        discount_price = (discount / 100) * float(product_price)
                        discount_amount = float(product_price) - discount_price
                        total += discount_amount * cart_item.quantity
                        quantity += cart_item.quantity


                tax = (2 * total) / 100
                grand_total = total + shipping + tax

                if 'disc_total' in request.session:
                    grand_total = request.session['disc_total']
                    del request.session['disc_total']

                if wallet.wallet < grand_total:
                    messages.error(request, "Insufficient funds in the wallet.")
                    return redirect("orders:checkout")
                
                wallet.wallet -= grand_total
                wallet.save()

templates/profile/address.html
{% extends "base.html" %}


{% block body %}

<style>
    
    .img-account-profile {
        height: 10rem;
    }
    .rounded-circle {
        border-radius: 50% !important;
    }
    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }
    .card .card-header {
        font-weight: 500;
    }
    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }
    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }
    .form-control, .dataTable-input {
        display: block;
        width: 100%;
        padding: 0.875rem 1.125rem;
        font-size: 18px;
        font-weight: 400;
        line-height: 1;
        color: #00000;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #c5ccd6;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.35rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }
    
    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }
    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }
    .g-brd-around {
        border: 1px solid #ddd;
        border-radius: 8px;
      }
</style>

<div class="container-xl px-4 mt-4" style="margin-bottom:60px;">
    <!-- Account page navigation-->
    <nav class="nav nav-borders">
        <a class="nav-link " href="{% url "user_profile:profile" %}">Profile</a>
        <a class="nav-link active " href="#">Address</a>
        <a class="nav-link" href="{% url "user_profile:order-track" %}" >Orders</a>
        <a class="nav-link" href="{% url "user_profile:rewards" %}"  >Rewards</a>
        <a class="nav-link" href="{% url "user_profile:wallet" %}">Wallet</a>
        <a class="nav-link" href="{% url "user_profile:wishlist" %}">Wishlist</a>
    </nav>
    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-xl-4">
            <!-- Profile picture card-->
            <div class="card mb-4 mb-xl-0">
                <div class="card-header">Profile Picture</div>
                <div class="card-body text-center">
                    <!-- Profile picture image-->
                    <img class="img-account-profile rounded-circle mb-2" src="{{profile.profile.url}}" alt="">
                    <!-- Profile picture help block-->
                    <h3>{{profile.first_name|default:''}} {{profile.last_name|default:''}}</h3>

                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <p class="text h5 text-success">{{ message }}</p>
                    {% else %}
                        <p class="text h5 text-danger">{{ message }}</p>
                    {% endif %}
                    {% endfor %}

                    

                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <!-- Account details card-->
            <div class="container">
                <div class="col-lg-9 g-mb-50">
                    <!-- Address 1 -->
                    {% for address in user_address %}
                    <div class="card mb-4 g-brd-around g-brd-gray-light-v4 rounded">
                        <div class="card-body">
                            <h3 class="h5 mb-3 d-flex align-items-center">
                                Address {{forloop.counter}}
                                <span class="badge badge-primary ml-3">Default</span>
                            </h3>
                            <i class="fa-solid fa-user" style="color: #000000;"></i> <b>{{profile.first_name}}</b>
                            <span class="d-block font-weight-bold mb-2"></span>

                            <address class="media mb-4">
                               
                                
                                <i class="fa-solid fa-map-location" style="color: #0c0d0d;"></i> <b>Address</b>
                                <div class="media-body g-color-text" style="width:209px;">
                                   {{address.address}},{{address.hometown}},{{address.district}},{{address.zipcode}}
                                </div>
                            </address>

                            <div class="media mb-4">
                            
                                <i class="fa-solid fa-mobile-retro" style="color: #030303;"></i> <b>Mobile</b>
                                
                                <div class="media-body g-color-text">
                                    {{profile.mobile_number}} , {{address.phone}}
                                </div>
                            </div>
                            
                            
                           
                            <br>
                            <a href="" data-bs-toggle="modal" data-bs-target="#addEmployeeModal-{{forloop.counter}}" class="btn btn-warning btn-sm" ><i class="fa-solid fa-pen-to-square" style="color: #000000;"></i></a>
                            <a href="{% url "user_profile:delete_address" address.id %}" class="btn btn-danger btn-sm" ><i class="fa-solid fa-trash" style="color: #000000;"></i></a>

                        </div>
                    </div>
                    {% endfor %}
                    <!-- End Address 1 -->
                    {% for x in user_address  %}
                    <div id="addEmployeeModal-{{forloop.counter}}" class="modal fade">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <form action='{% url "user_profile:update_address" x.id %}' method="post" >
                                {% csrf_token %}
                                    <div class="modal-header">						
                                        <h4 class="modal-title">Edit Address</h4>
                                        
                                    </div>
                    
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label>District</label>
                                            <input name="district" type="text" class="form-control" required value="{{x.district}}">
                                        </div>
                    
                                        <div class="form-group">
                                            <label>Hometown</label>
                                            <input name="hometown" type="text" class="form-control" required value="{{x.hometown}}">
                                        </div>
                    
                                        
                                        <div class="form-group">
                                            <label>Zipcode</label>
                                            <input name="zipcode" type="text" class="form-control" required value="{{x.zipcode}}">
                                        </div>
                    
                                        <div class="form-group">
                                            <label>Address</label>
                                            <input name="address" type="text" class="form-control" required value="{{x.address}}">
                                        </div>

                                        <div class="form-group">
                                            <label>Additional Phone</label>
                                            <input name="phone" type="text" class="form-control" required value="{{x.phone}}">
                                        </div>

                                        

                    
                                        
                                        
                                    </div>
                                    <div class="modal-footer">
                                        <input type="button" class="btn btn-danger" data-dismiss="modal" value="Cancel">
                                        <input type="submit" class="btn btn-success" value="Save changes"> 
                                         
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    <!-- Add Address Form -->
                    <div class="card mb-4 g-brd-around g-brd-gray-light-v4 rounded">
                        <div class="card-body">
                            <h3 class="h5 mb-3">Add Address</h3>
                            <form method="post" action="{% url "user_profile:add_address" %}">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-sm-6 form-group mb-4">
                                        <label class="g-color-text g-font-size-13">District</label>
                                        <input class="form-control" type="text" required name="district" placeholder="District">
                                    </div>

                                    <div class="col-sm-6 form-group mb-4">
                                        <label class="g-color-text g-font-size-13">Hometown</label>
                                        <input class="form-control" type="text" required name="hometown" placeholder="hometown">
                                    </div>

                                    <div class="col-sm-6 form-group mb-4">
                                        <label class="g-color-text g-font-size-13">Zip Code</label>
                                        <input class="form-control" type="text" required name="zipcode" placeholder="Zip Code">
                                    </div>

                                    <div class="col-sm-6 form-group mb-4">
                                        <label class="g-color-text g-font-size-13">Address</label>
                                        <input class="form-control" type="text" required name="address" placeholder="Address">
                                    </div>

                                    <div class="col-sm-6 form-group mb-4">
                                        <label class="g-color-text g-font-size-13">Additional Phone (optional)</label>
                                        <input class="form-control" type="text" required name="phone" placeholder="Additional Phone number (optional)">
                                    </div>
                                    
                                </div>
                                
                                <button class="btn btn-dark" type="submit">Add Address</button>
                            </form>
                            
                        </div>
                    </div>
                    <!-- End Add Address Form -->

                </div>
            </div>

            <!-- End Contact Form -->

           
        </div>
    </div>
</div>

{% endblock %}

templates/profile/cancel_order.html
{% extends "base.html" %}

{% block body %}
<div class="container-xl px-4 mt-4" style="margin-bottom:60px;">
    <!-- Add your existing content here -->

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="mb-0">Cancel Order</h5>
                </div>
                <div class="card-body">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="cancelReason" class="form-label">Reason for Cancellation</label>
                            <textarea class="form-control" min=50 required id="cancelReason" name="cancel_reason" rows="4" required></textarea>
                            {% for x in messages %}
                            <label style="color:red;" for="cancelReason" class="form-label">{{x}}</label>
                            {% endfor %}
                        </div>
                        
                        <button type="submit" class="btn btn-danger">Cancel Order</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/profile/return.html
{% extends "base.html" %}

{% block body %}
<div class="container-xl px-4 mt-4" style="margin-bottom:60px;">
    <!-- Add your existing content here -->

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="mb-0">Return Order</h5>
                </div>
                <div class="card-body">
                    <form method="post" action="{% url "user_profile:return_order" order.id %}">
                        {% csrf_token %}
                        
                     
                        <div class="mb-3">
                            <label for="refundMethod" class="form-label">If you want to return only one product just select that product else the whole product will be returned </label>
                            <select class="form-select"  name="item" required>
                                <option value="" selected disabled > Select what to return</option>
                                <option value="All"> All</option>
                                {% for x in order_products %}
                                <option value="{{x.id}}">{{x.product.product_name}}</option>
                                {% endfor %}
                                <!-- Add more options as needed -->
                            </select>
                        </div>

                        <div class="mb-3">
                            <label for="cancellationReason" class="form-label">Cancellation Reason</label>
                            <select class="form-select" id="cancellationReason" name="cancellation_reason" required>
                                <option value="" selected disabled>Select a reason</option>
                                <option value="unavailable">Product is unavailable</option>
                                <option value="change_mind">Changed my mind</option>
                                <option value="size_not_correct">Incorrect Size</option>
                                <option value="item_damaged">Item Damaged</option>
                                <option value="wrong_color">Wrong Product</option>
                                <option value="received_late">Received Late</option>
                                <option value="found_cheaper">Found Cheaper Price Elsewhere</option>

                                <!-- Add more options as needed -->
                            </select>
                        </div>

                        <!-- Reason for cancellation textarea -->
                        <div class="mb-3">
                            <label for="cancelReason" class="form-label">Reason for Cancellation</label>
                            <textarea class="form-control" min=50 required id="cancelReason" name="detail_reason" rows="4" required></textarea>

                            {% for x in messages %}
                                <label style="color:red;" for="cancelReason" class="form-label">{{x}}</label>
                            {% endfor %}
                        </div>
                        
                        <button type="submit" class="btn btn-danger">Return</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}