Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    
    path('user/', include('User_auth.urls')),
    path('', include('main.urls')),
    path('cadmin/', include('adminside.urls')),
    path('products/', include('products.urls')),
    path('cart/',include('cart.urls')),
    path('user_profile/',include('user_profile.urls')),
    path('checkout/',include('orders.urls')),
    path('coupons/',include('coupons.urls')),
    path('offers/',include('offers.urls')),
    
    

   
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import include, path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:id>/", views.add_cart, name="add_cart"),
    path("remove_cart/<int:id>/", views.remove_cart, name="remove_cart"),
    path("delete_cart_item/<int:id>/", views.delete_cart_item, name="delete_cart_item"),
    path("update_cart/", views.update_cart, name="update_cart"),
]

orders/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.checkout ,name="checkout"),
    path('place_order/', views.place_order ,name="place_order"),
    path('coupon-applied/', views.apply_coupon ,name="apply_coupon"),
    path('list_order/', views.list_order ,name="list_orders"),
    path('change-status/<int:id>/', views.change_status ,name="change_status"),
    path('view-order/<int:id>/', views.view_order, name="view_order"),
    path('remove/<int:id>/', views.soft_remove, name="soft_remove"),
    path('delete/<int:id>/', views.order_delete, name="order_delete"),
    path('place-order/', views.place_order,name="online_payment"),
    path('online-payment/', views.online_payment ,name="online_payment_sucsses"),
    path('order-succssesfull/', views.order_sucsses ,name="order_sucsses"),
    path('submit-review/<int:id>/', views.submit_review ,name="submit_review"),
    

    

    
    
]

cart/models.py
from adminside.models import Custom_user
from django.db import models
from products.models import *


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(blank=True, max_length=250)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.cart_id


class Cartitem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    size = models.CharField(null=True, max_length=25)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def subtotal(self):
        return self.product.price * self.quantity

    def __str__(self) -> str:
        return self.product.product_name

cart/views.py
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from offers.models import *
from products.models import *

from .models import *

# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        shipping = 0
        if not request.user.is_authenticated:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            print(cart.cart_id, "caridfaklds")
            cart_items = Cartitem.objects.filter(cart=cart, is_active=True)
        else:
            cart_items = Cartitem.objects.filter(user=request.user, is_active=True)

        for cart_item in cart_items:
            product_price = cart_item.product.price
            product_offer = cart_item.product.offer
            category_offer = cart_item.product.category.offer

            if product_offer is None and category_offer is None:
                total += cart_item.product.price * cart_item.quantity
                quantity += cart_item.quantity
            else:
                if product_offer and category_offer:
                    discount = max(product_offer.discount, category_offer.discount)
                elif product_offer:
                    discount = product_offer.discount
                else:
                    discount = category_offer.discount
                discount_price = (discount / 100) * float(product_price)
                discount_amount = float(product_price) - discount_price
                total += discount_amount * cart_item.quantity
                quantity += cart_item.quantity

        tax = (2 * total) / 100
        shipping = 20
        grand_total = total + shipping + tax

    except ObjectDoesNotExist:
        pass

    context = {
        "total": total,
        "quantity": quantity,
        "cart_items": cart_items,
        "tax": tax,
        "shipping": shipping,
        "grandtotal": grand_total,
    }

    return render(request, "cart/cart.html", context)


def add_cart(request, id):
    print(id, "id")
    product = Products.objects.get(id=id)
    if not request.user.is_authenticated:
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))

        cart.save()
        try:
            cart_item = Cartitem.objects.get(product=product, cart=cart)
            cart_item.quantity += 1
            cart_item.save()
        except Cartitem.DoesNotExist:
            cart_item = Cartitem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            cart_item.save()

        return redirect("cart:cart")

    else:
        try:
            cart_item = Cartitem.objects.get(product=product, user=request.user)
            cart_item.quantity += 1
            cart_item.save()
        except Cartitem.DoesNotExist:
            cart_item = Cartitem.objects.create(
                user=request.user,
                product=product,
                quantity=1,
            )
            cart_item.save()

        return redirect("cart:cart")


def update_cart(request):
    if request.method == "POST":
        try:
            product_id = int(request.POST.get("product_id"))
            action = request.POST.get("action")
            product_qty = int(request.POST.get("quantity", 0))

            cart_item = get_object_or_404(
                Cartitem, user=request.user, product_id=product_id
            )

            if product_qty == 0:
                return redirect("cart:cart")

            if product_qty > cart_item.product.stock:
                return JsonResponse(
                    {"status": "Requested quantity exceeds available quantity"}
                )

            cart_item.quantity = product_qty
            cart_item.save()

            if not request.user.is_authenticated:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                cart_items = Cartitem.objects.filter(cart=cart, is_active=True)
            else:
                cart_items = Cartitem.objects.filter(user=request.user, is_active=True)

            total = 0
            quantity = 0

            for cart_item in cart_items:
                product_price = float(cart_item.product.price)
                product_offer = cart_item.product.offer
                category_offer = cart_item.product.category.offer

                if product_offer is None and category_offer is None:
                    total += product_price * cart_item.quantity
                    quantity += cart_item.quantity
                else:
                    if product_offer and category_offer:
                        discount = max(product_offer.discount, category_offer.discount)
                    elif product_offer:
                        discount = product_offer.discount
                    else:
                        discount = category_offer.discount

                    discount_price = (discount / 100) * product_price
                    discounted_price = product_price - discount_price

                    total += discounted_price * cart_item.quantity
                    quantity += cart_item.quantity

            tax = (2 * total) / 100
            shipping = 20
            grand_total = total + shipping + tax

            single_price = product_price * cart_item.quantity

            return JsonResponse(
                {
                    "status": "Cart Updated Successfully",
                    "single_price": single_price,
                    "grand_total": grand_total,
                    "tax": tax,
                    "shipping": shipping,
                }
            )
        except ObjectDoesNotExist:
            pass

    return JsonResponse({"status": "Invalid request method"})


def remove_cart(request, id):
    if not request.user.is_authenticated:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        product = get_object_or_404(Products, id=id)
        cart_item = Cartitem.objects.get(product=product, cart=cart)

        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
        return redirect("cart:cart")
    else:
        product = get_object_or_404(Products, id=id)
        cart_item = Cartitem.objects.get(product=product, user=request.user)

        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
        return redirect("cart:cart")


def delete_cart_item(request, id):
    if not request.user.is_authenticated:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        product = get_object_or_404(Products, id=id)
        cart_item = Cartitem.objects.get(product=product, cart=cart)
        cart_item.delete()

        return redirect("cart:cart")
    else:
        product = get_object_or_404(Products, id=id)
        cart_item = Cartitem.objects.get(product=product, user=request.user)
        cart_item.delete()

        return redirect("cart:cart")

templates/cart/cart.html
{% extends "base.html" %}
{% load static %}

{% block body %}
   

    <div class="f_cart_area pt-110 mb-100">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-md-12">
                    <div class="cart_table">
                        <table>
                            
                            <tr> 
                                <td>Product</td>
                                <td></td>
                                <td style="padding: 30px;" >price</td>
                                <td>Quantity</td>
                                <td style="padding: 30px;">Total</td>
                                
                               </tr>
                            <tbody>
                                {% for cart_item in cart_items %}
                                <tr class="max-width-set">
                                    <td>
                                        <img src="{{cart_item.product.image.url}}" alt="">
                                    </td>
                                    {% if cart_item.product.stock <= 0 %}
                                    <td class="text text-danger">Out of Stock</td>
                                    {% else %}
                                    <td>{{cart_item.product.product_name}}</td>
                                    {% endif %}
                                    {% if cart_item.product.offer or cart_item.product.category.offer %}
                                    <td style="color:green;">$ {{cart_item.product.get_offer}} &nbsp<span style="color:red;"><s>${{cart_item.product.price}}</s><span></td>
                                    
                                    {% else %}
                                    <td>$ {{cart_item.product.price}}</td>
                                    {% endif %}
                                    <td>


                                    <div class="col">
                                        <div class="input-group input-spinner" style="justify-content: center;">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light changequantity" data-action="decrement" data-product-id="{{cart_item.product.id}}"  style="background-color:#e2e3e4;" type="button" id="button-plus" > <i class="fa fa-minus"></i> </button>
                                            </div>
                                            <input type="number" class="form-controls" min="1" readonly value="{{cart_item.quantity}}" id="product_qty{{cart_item.product.id}}" style="width: 76px; text-align: center;">
                                            <div class="input-group-append">
                                                <button  class="btn btn-light changequantity" data-action="increment" data-product-id="{{cart_item.product.id}}" style="background-color:#e2e3e4;" type="button" id="button-minus"> <i class="fa fa-plus"></i> </button>

                                            </div>
                                        </div>
                                    </div>


                                    
                                    </td>
                                     <td>
                                    <div id="singlePriceDisplay{{cart_item.product.id}}">
                                       
                                       $ {{cart_item.subtotal}}

                                    </div>
                                    </td>
                                    <td class="width-set">
                                        <a href="{% url 'cart:delete_cart_item' cart_item.product.id %}"><i
                                            class="fal fa-times-circle"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr class="design-footer">
                                    <td>
                                        <input type="text" placeholder="Coupon Code">
                                    </td>
                                    <td><button type="submit">Apply Coupon</button></td>
                                    <td colspan="3"><a href="#">update cart</a></td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-4 col-md-12">
                    <div class="cart__acount">
                        <h5>Cart totals</h5>
                      <table>
                        <tr class="first-child">
                            <td>Tax</td>
                            <td id="taxDisplay">${{tax}}</td>
                        </tr>
                        <tr class="first-child lastchild">
                            <td>Shipping</td>
                            <td>Shipping includes ${{shipping}}</td>
                        </tr>
                        <tr class="first-child">
                            <td>Grand Total</td>
                            <td>
                                {% if tax == 0 %}
                                    $
                                {% else %}
                                    <div id="grandTotalDisplay">${{grandtotal}}</div>
                                {% endif %}
                            </td>
                        </tr>
                          <tr>   
                              <td colspan="2">
                               
                                <a href="{% url "orders:checkout" %}"><input type="submit" value="procced to checkout"></a>
                                
                                {% for message in messages %}
                                <p>{{message}}</p>
                                {% endfor %}
                               
                              </td>
                          </tr>
                      </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


<!-- Error Modal -->
<div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="errorModalLabel">Messages</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p id="errorMessage"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% if messages %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Check if there are error messages
        var errorMessages = "{% for message in messages %}{{ message }}{% endfor %}".trim();
        if (errorMessages !== "") {
            // Set the error message in the modal
            document.getElementById('errorMessage').textContent = errorMessages;

            // Show the error modal
            var errorModal = new bootstrap.Modal(document.getElementById('errorModal'));
            errorModal.show();
        }
    });
</script>
{% endif %}

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.19/dist/sweetalert2.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>



<script>
    document.addEventListener('DOMContentLoaded', function() {
        $('.changequantity').off('click').click(function(e) {
            e.preventDefault();
            var action = $(this).data('action');
            var productId = $(this).data('product-id');
            var input = $('#product_qty' + productId);
            var qty = parseInt(input.val(), 10) || 0;
            console.log(productId);
            if (action === 'increment') {
                qty += 1;
            } else if (action === 'decrement' && qty > 0) {
                qty -= 1;
            }

            $.ajax({
                method: "POST",
                url: "{% url 'cart:update_cart' %}",
                data: {
                    'product_id': productId,
                    'quantity': qty,
                    'action': action,
                    'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val()
                },
                success: function(response) {
                    if (response.status === 'Requested quantity exceeds available quantity') {
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: response.status,
                            footer: '<a href="">Why do I have this issue?</a>'
                        });

                    } else if (response.status === 'Zero quantity not allowed' || response.status === 'Invalid request method') {
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: response.status,
                            footer: '<a href="">Why do I have this issue?</a>'
                        });
                    } else {
                        // Update single price and grand total
                        if (qty === 0) {
                            // If the quantity becomes zero, set it to 1
                            qty = 1;
                        }

                        // Update the quantity in the text field
                        input.val(qty);

                        // Update single price and grand total
                        $('#singlePriceDisplay' + productId).text(response.single_price);
                        $('#grandTotalDisplay').text(response.grand_total);
                        if (response.tax !== undefined) {
                            $('#taxDisplay').text('$' + response.tax);
                        } else {
                            $('#taxDisplay').text('$6.00');
                        }
                        $('#shippingDisplay').text('Shipping includes $' + response.shipping);
                    }
                },
                error: function(error) {
                    alert("Error updating cart.");
                }
            });
        });
    });
</script>





    {% endblock body %}