Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    
    path('user/', include('User_auth.urls')),
    path('', include('main.urls')),
    path('cadmin/', include('adminside.urls')),
    path('products/', include('products.urls')),
    path('cart/',include('cart.urls')),
    path('user_profile/',include('user_profile.urls')),
    path('checkout/',include('orders.urls')),
    path('coupons/',include('coupons.urls')),
    path('offers/',include('offers.urls')),
    
    

   
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import include, path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:id>/", views.add_cart, name="add_cart"),
    path("remove_cart/<int:id>/", views.remove_cart, name="remove_cart"),
    path("delete_cart_item/<int:id>/", views.delete_cart_item, name="delete_cart_item"),
    path("update_cart/", views.update_cart, name="update_cart"),
]

products/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "products"

urlpatterns = [
    path("manage_products/", views.manage_products, name="manage_products"),
    path("add_products/", views.add_products, name="add_products"),
    path("edit_products/<int:id>/", views.edit_product, name="edit_products"),
    path("update_product/<int:id>/", views.update_product, name="update_product"),
    path("remove_product/<int:id>/", views.remove_product, name="remove_product"),
    path("delete_product/<str:id>/", views.delete_product, name="delete_product"),
    path("view_product/<int:id>/", views.view_product, name="view_product"),
]

products/models.py
from decimal import Decimal

from adminside.models import *
from django.db import models
from django.db.models import Avg, Count
from offers.models import *
from user_profile.models import *


# Create your models here.
class Products(models.Model):
    product_name = models.CharField(unique=True, max_length=100)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True
    )  # foriegn key
    subcategory = models.CharField(null=True, max_length=50)
    offer = models.ForeignKey(Offer, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField()
    stock = models.IntegerField()
    sizes = models.CharField(null=True, max_length=50)
    brand = models.ForeignKey(
        Brand, on_delete=models.SET_NULL, null=True
    )  # foriegn key
    price = models.DecimalField(max_digits=10, decimal_places=2)
    return_time = models.CharField(default="Return not available", max_length=50)
    meterial = models.CharField(default="NA", max_length=200)
    warranty = models.CharField(default="NA", max_length=50)
    image = models.ImageField(
        upload_to="products/", default="No images available", blank=True
    )
    special = models.BooleanField(default=False)
    offer_pro = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)
    added_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.product_name

    def get_offer(self):
        product_offer = self.offer
        category_offer = self.category.offer

        if (
            product_offer
            and not product_offer.is_offer_expired()
            and category_offer
            and not category_offer.is_offer_expired()
        ):
            max_discount = max(
                Decimal(product_offer.discount), Decimal(category_offer.discount)
            )
            discount = (max_discount / Decimal(100)) * Decimal(self.price)
            discount_amount = Decimal(self.price) - discount
            return float(discount_amount)

        elif product_offer and not product_offer.is_offer_expired():
            discount = (Decimal(product_offer.discount) / Decimal(100)) * Decimal(
                self.price
            )
            discount_amount = Decimal(self.price) - discount
            return float(discount_amount)

        elif category_offer and not category_offer.is_offer_expired():
            discount = (Decimal(category_offer.discount) / Decimal(100)) * Decimal(
                self.price
            )
            discount_amount = Decimal(self.price) - discount
            return float(discount_amount)

        else:
            return float(self.price)

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(
            average=Avg("rating")
        )
        avg = 0
        if reviews["average"] is not None:
            avg = float(reviews["average"])
            return avg

    def count_reviews(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(
            count=Count("rating")
        )
        count = 0
        if reviews["count"] is not None:
            count = int(reviews["count"])
        return count


class MultipleImage(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    images = models.ImageField(
        upload_to="products/", default="No images available", blank=True
    )

    def __str__(self) -> str:
        return f"Image for {'self.product.product_name'}"


class ReviewRating(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(User_profile, on_delete=models.CASCADE)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(blank=True, max_length=50)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.user.username}'s review on {self.product.product_name}"


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"whishlist of {self.user.username}"

products/views.py
from adminside.models import Category
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import *
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .models import *

# Create your views here.


@login_required(login_url="adminside:cadmin_login")
def manage_products(request):
    products = Products.objects.all()
    search = request.GET.get("search")

    if search:
        # Use Q objects to perform case-insensitive search
        products = Products.objects.filter(
            Q(product_name__icontains=search)
            | Q(brand__name__icontains=search)
            | Q(  # Use brand__name__icontains to search for brand name
                category__name__icontains=search
            )  # Use category__name__icontains to search for category name
        )

    context = {
        "products": products,
    }

    return render(request, "products/products.html", context)


@login_required(login_url="adminside:cadmin_login")
def add_products(request):
    brands = Brand.objects.filter(is_available=True)
    categories = Category.objects.filter(is_available=True)
    offers = Offer.objects.filter(is_active=True)
    context = {"categories": categories, "brands": brands, "offers": offers}

    if request.method == "POST":
        product_name = request.POST["product_name"]
        category = request.POST["category"]
        sub_category = request.POST["sub_category"]
        description = request.POST["description"]
        stocks = request.POST["stocks"]
        sizes = request.POST["sizes"]
        brand = request.POST["brand"]
        price = request.POST["price"]
        return_time = request.POST["return"]
        material = request.POST["material"]
        warranty = request.POST["warranty"]
        offer = request.POST.get("offer", None)
        product_img = request.FILES.get("product_image")
        additional_images = request.FILES.getlist("additional_images")
        special = request.POST.get("special", False)
        offer_pro = request.POST.get("has_offer")

        if "special" in request.POST:
            special = request.POST["special"] == "on"
        else:
            special = False

        if (
            not product_name
            or not category
            or not description
            or not stocks
            or not sizes
            or not brand
            or not price
        ):
            messages.error(request, "All required fields must be filled.")
            return redirect("products:add_products")

        if Products.objects.filter(product_name=product_name).exists():
            messages.info(request, "Product with this name already exists !!")

        elif not product_img or not additional_images:
            messages.error(request, "Product image and additional images are required.")

        else:
            if len(additional_images) < 3:
                messages.error(
                    request, "You can upload a maximum of three additional images."
                )

            else:
                cat = Category.objects.get(id=category)
                br = Brand.objects.get(id=brand)
                offer_item = None
                if offer:
                    offer_item = Offer.objects.get(id=offer)
                product = Products(
                    product_name=product_name,
                    category=cat,
                    subcategory=sub_category,
                    description=description,
                    stock=stocks,
                    sizes=sizes,
                    brand=br,
                    offer=offer_item,
                    price=price,
                    return_time=return_time,
                    meterial=material,
                    warranty=warranty,
                    image=product_img,
                    special=special,
                )
                product.save()

                if offer:
                    product.offer_pro = True
                    product.save()

                for image in additional_images:
                    print(image, "image")
                    additional_image = MultipleImage.objects.create(
                        product=product, images=image
                    )
                    additional_image.save()
                messages.info(request, "Product added sucssesfully ")

                return redirect("products:manage_products")

    return render(request, "products/addproducts.html", context)


@login_required(login_url="adminside:cadmin_login")
def remove_product(request, id):
    product = Products.objects.get(id=id)
    if product.is_available:
        product.is_available = False
    else:
        product.is_available = True

    product.save()
    return redirect("products:manage_products")


@login_required(login_url="adminside:cadmin_login")
def delete_product(request, id):
    product = Products.objects.get(id=id)
    product.delete()
    return redirect("products:manage_products")


@login_required(login_url="adminside:cadmin_login")
def edit_product(request, id):
    product = Products.objects.get(id=id)
    category = Category.objects.all()
    brand = Brand.objects.all()
    offers = Offer.objects.all()

    context = {
        "product": product,
        "categories": category,
        "brand": brand,
        "offers": offers,
    }

    return render(request, "products/editproducts.html", context)


@login_required(login_url="adminside:cadmin_login")
def update_product(request, id):
    if request.method == "POST":
        product_name = request.POST["product_name"]
        category = request.POST["category"]
        sub_category = request.POST["sub_category"]
        description = request.POST["description"]
        stocks = request.POST["stocks"]
        sizes = request.POST["sizes"]
        brand = request.POST["brand"]
        offer = request.POST["offer"]
        price = request.POST["price"]
        return_time = request.POST["return"]
        material = request.POST["material"]
        warranty = request.POST["warranty"]
        product_img = request.FILES.get("product_image")
        additional_images = request.FILES.getlist("additional_images")

        if product_img:
            product = Products.objects.get(id=id)
            cat = Category.objects.get(id=category)
            br = Brand.objects.get(id=brand)
            if offer:
                offer_obj = Offer.objects.get(id=offer)
                product.offer_pro = True
                product.save()
            else:
                offer_obj = None

            product.offer = offer_obj
            product.product_name = product_name
            product.category = cat
            product.sub_category = sub_category
            product.description = description
            product.stock = stocks
            product.sizes = sizes
            product.brand = br
            product.price = price
            product.return_time = return_time
            product.meterial = material
            product.warranty = warranty
            product.image = product_img

            product.save()

        else:
            product = Products.objects.get(id=id)
            cat = Category.objects.get(id=category)
            br = Brand.objects.get(id=brand)
            if offer:
                offer_obj = Offer.objects.get(id=offer)
                product.offer_pro = True
                product.save()
            else:
                offer_obj = None
            product.offer = offer_obj
            product.product_name = product_name
            product.category = cat
            product.sub_category = sub_category
            product.description = description
            product.stock = stocks
            product.sizes = sizes
            product.brand = br
            product.price = price
            product.return_time = return_time
            product.meterial = material
            product.warranty = warranty

            product.save()

        if additional_images:
            product.multipleimage_set.all().delete()

            for image in additional_images:
                multi_images = MultipleImage(product=product, images=image)
                multi_images.save()

        messages.success(request, "Product edited Sucssesfully")

        return redirect("products:manage_products")


@login_required(login_url="adminside:cadmin_login")
def view_product(request, id):
    product = Products.objects.get(id=id)
    multiimg = MultipleImage.objects.filter(product=id)
    context = {"product": product, "images": multiimg}
    return render(request, "products/viewproducts.html", context)

templates/products/editproducts.html
{% extends "admin/adminbase.html" %}
{% load static %}

{% block body %}
<div class="row">
  <div class="col-12 grid-margin stretch-card">   
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Edit Products</h4>
            <p class="card-description">
            The information that you enter here will be appeard on Products details page , so wisely enter all details
            </p>
            <br>
            {% for message in messages %}
        
            <h6 class="text text-danger">{{message}}</h6>
        
            {% endfor %}
            <br>

    <!--------------------------------------------form starts------------------------------------------------------------------------>        
            
        <form class="forms-sample" method="post" action='{% url "products:update_product" product.id %}' enctype="multipart/form-data">
                {% csrf_token %}

            <div class="form-group">
                <label for="exampleInputName1">Product Name</label>
                <input type="text" value="{{product.product_name}}" name="product_name" class="form-control" id="exampleInputName1" placeholder="Name">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail3">Category</label>
                <select class="form-control" name="category" id="exampleSelectGender">
                    {% for x in categories %}
                    <option value="{{x.id}}" {% if x.id == product.category.id %}selected{% endif %}>{{x.name}}</option>
                    {% endfor %}
                </select>   
            </div>

            <div class="form-group">
                <label for="exampleInputEmail3">Sub Category <span> ( eg: running , casuals , formals ) </span> </label>
                <select class="form-control" value="{{product.sub_category}}" name="sub_category" id="exampleSelectGender">
                    <option>Casuals</option>
                    <option>Formals</option>
                    <option>Running</option>
                    <option>Boots</option>
                </select>
            </div>

            <div class="form-group">
                <label for="exampleTextarea1">Description</label>
                <textarea class="form-control" value="" name="description" pattern=".{100,}" title="The description must be at least 100 characters" id="exampleTextarea1" rows="4">{{product.description}}</textarea>
                <span id="exampleTextarea"></span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword4">Available stocks </label>
                <input type="number" value="{{product.stock}}" name="stocks" class="form-control" id="exampleInputPassword4" placeholder="">
            </div>
            
            <div class="form-group">
                <label for="exampleInputPassword4">Availabel Sizes </label>
                <input type="text" value="{{product.sizes}}" name="sizes" class="form-control" id="exampleInputPassword4" placeholder="">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword4">Select available Brand</label>
                <select class="form-control" name="brand" id="exampleSelectGender">
                        {% for x in brand %}
                        <option value="{{x.id}}" {% if x.id == product.brand.id %}selected{% endif %}>{{x.name}}</option>
                        {% endfor %}
                </select>  
            </div>

            <div class="form-group">
                <label for="exampleInputPassword4">Select Offer</label>
                <select class="form-control" name="offer" id="exampleSelectGender">
                    <option value="">Select offer</option>
                    {% for x in offers %}
                        <option value="{{ x.id }}" {% if x.id == product.offer.id %}selected{% endif %}>{{ x.name }}</option>
                    {% endfor %}
                </select>  
            </div>
            


            <div class="form-group">
                <label for="exampleInputPassword4">Price</label>
                <input type="number" value="{{product.price}}" name="price" class="form-control" id="exampleInputPassword4" placeholder="">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword4">Return Upto</label>
                <input type="text" value="{{product.return_time}}" name="return" class="form-control" id="exampleInputPassword4" placeholder="">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword4">Material</label>
                <input type="text" value="{{product.meterial}}" name="material" class="form-control" id="exampleInputPassword4" placeholder="">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword4">Warranty Upto</label>
                <input type="text" value="{{product.warranty}}" name="warranty" class="form-control" id="exampleInputPassword4" placeholder="">
            </div>

            <div class="form-group">
                <label>Upload Thumbnail image</label>
                <input value="{{product.product_image}}" name="product_image" type="file" accept="image/png, image/jpeg, image/svg, image/avif, image/WEBP" class="form-control"id="image-input"  accept="image/*" />
                <small id="image-error" class="text-danger text-center"></small>
            </div>

            <div class="form-group">
                <label>Add other Images (max:3)</label>
                <input value="{{product.additional_images}}" name="additional_images" multiple type="file" accept="image/png, image/jpeg, image/svg, image/avif, image/WEBP" class="form-control"id="image-input"  accept="image/*" />
                <small id="image-error" class="text-danger text-center"></small>
            </div>

            <div class="form-check">
                <label class="form-check-label">
                    <input type="checkbox" {% if product.special %}checked{% endif %} name="special" class="form-check-input">
                    Special Product
                </label>
            </div>
            
            <div class="form-check">
                <label class="form-check-label">
                    <input type="checkbox" {% if product.offer_pro %}checked{% endif %} name="offer_pro" class="form-check-input">
                    Offered Product
                </label>
            </div>
            

            <br>
            
            <button type="submit" class="btn btn-primary mr-2">Submit</button>
            <button class="btn btn-light">Cancel</button>
        </form>

     <!-------------------------------------------------form ends ------------------------------------------------------------------------>

        </div>
       </div>
  </div>  

</div>

{% endblock body %}

templates/products/products.html
{% extends "admin/adminbase.html" %}
{% load static %}

{% block body %}
<style>
  @import url("https://fonts.googleapis.com/css2?family=Poppins:weight@100;200;300;400;500;600;700;800&display=swap");


  body{
   background-color:#eee;
   font-family: "Poppins", sans-serif;
   font-weight: 300;
  }

  .height{
   height: 12vh;
  }
  

  .search{
  position: relative;
  box-shadow: 0 0 40px rgba(51, 51, 51, .1);
  right:14px;
    
  }

  .search input{

   height: 45px;
   text-indent: 25px;
   border: 2px solid #d6d4d4;


  }


  .search input:focus{

   box-shadow: none;
   border: 2px solid blue;


  }

  .search .fa-search{

   position: absolute;
   top: 20px;
   left: 16px;

  }

  .search button{

   position: absolute;
   top: 1px;
   right: 1px;
   height: 43px;
   width: 112px;
   background: blue;
   border-radius: 0;

  }

</style>


        <div class="card-body">
            <h4 class="card-title">Manage Your Products</h4>
            <br>
            <a href="{% url "products:add_products" %}" class="btn btn-primary btn-sm">
                Add Products
            </a>
            <br>
            <br>
            {% for message in messages  %}
            <h6 class="text text-success">{{message}}</h6>
            {% endfor %}
            <br>
            <div class="container">

              <div class="row height d-flex justify-content-start align-items-center">
        
                <div class="col-md-8">
        
                  <div class="search">
                    <i class="fa fa-search"></i>
                    <form method="get" action={% url "products:manage_products" %}>
                      {% csrf_token %}
                    <input type="text" class="form-control" name="search" placeholder="Search users here">
                    <button class="btn btn-primary">Search</button>
                    </form>
                  </div>
                  
                </div>
                
              </div>
          </div>
            
          <div class="row">
            <div class="col-12">
              <div class="table-responsive">
                <table  class="display expandable-table" style="width:100%">
                  <thead>
                    <tr>
                      <th>Id</th>
                      <th>Product Name</th>
                      <th>Category</th>
                      <th>Brand</th>
                      <th>offer</th>
                      <th>Status</th>
                      <th>More</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for product in products  %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td>{{product.product_name}}</td>
                      <td>{{product.category}}</td>
                      <td>{{product.brand}}</td>
                      {% if product.offer %}
                      <td class="text text-success">Available</td>
                      {% else %}
                      <td class="text text-danger">Unavailable</td>
                      {% endif %}

                      {% if product.stock > 0 and  product.is_available %}
                      <td class="text text-success">Available</td>
                      {% elif not product.is_available %}
                      <td class="text text-warning">Removed</td>
                      {% else %}
                      <td class="text text-danger">Out of stock</td>
                      {% endif %}


                      <td><a href='{% url "products:view_product" product.id %}' class="btn btn-inverse-info btn-sm">view</td>
                      <td>
                        <a href="{% url "products:edit_products" product.id %}" class="btn btn-warning btn-sm">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                            </svg>
                        </a> 
                        
                        <a href="#deleteEmployeeModal-{{forloop.counter}}" data-toggle="modal" class="btn btn-danger btn-sm">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                            </svg>
                        </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
              </table>
              </div>
            </div>
        

            {% for x in products %}
                <div id="deleteEmployeeModal-{{forloop.counter}}" class="modal fade">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <form>
                        <div class="modal-header">						
                          <h4 class="modal-title">Delete Proudcts</h4>
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        </div>
                        <div class="modal-body">					
                          <p class="text fs-6">If you want to remove a Product from the site use Remove , else if you want to delete permently use delete </p>
                          <p class="text text-dark fs-6"><small>The Delete action cannot be undone , All details of the product will be Lost</small></p>
                        </div>
                        <div class="modal-footer">
                          {% if x.is_available %}
                          <a href="{% url "products:remove_product" x.id %}" type="submit" class="btn btn-info">Remove</a>
                          {% else %}
                          <a href="{% url "products:remove_product" x.id %}" type="submit" class="btn btn-info">Make visible</a>
                          {% endif %}
                          <a href="{% url "products:delete_product" x.id %}" type="submit" class="btn btn-danger">delete</a>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
	          {% endfor %}


{% endblock body %}