Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    
    path('user/', include('User_auth.urls')),
    path('', include('main.urls')),
    path('cadmin/', include('adminside.urls')),
    path('products/', include('products.urls')),
    path('cart/',include('cart.urls')),
    path('user_profile/',include('user_profile.urls')),
    path('checkout/',include('orders.urls')),
    path('coupons/',include('coupons.urls')),
    path('offers/',include('offers.urls')),
    
    

   
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import include, path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:id>/", views.add_cart, name="add_cart"),
    path("remove_cart/<int:id>/", views.remove_cart, name="remove_cart"),
    path("delete_cart_item/<int:id>/", views.delete_cart_item, name="delete_cart_item"),
    path("update_cart/", views.update_cart, name="update_cart"),
]

orders/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.checkout ,name="checkout"),
    path('place_order/', views.place_order ,name="place_order"),
    path('coupon-applied/', views.apply_coupon ,name="apply_coupon"),
    path('list_order/', views.list_order ,name="list_orders"),
    path('change-status/<int:id>/', views.change_status ,name="change_status"),
    path('view-order/<int:id>/', views.view_order, name="view_order"),
    path('remove/<int:id>/', views.soft_remove, name="soft_remove"),
    path('delete/<int:id>/', views.order_delete, name="order_delete"),
    path('place-order/', views.place_order,name="online_payment"),
    path('online-payment/', views.online_payment ,name="online_payment_sucsses"),
    path('order-succssesfull/', views.order_sucsses ,name="order_sucsses"),
    path('submit-review/<int:id>/', views.submit_review ,name="submit_review"),
    

    

    
    
]

user_profile/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "user_profile"

urlpatterns = [
    path("profile/", views.profile, name="profile"),
    path("update-profile/", views.update_profile, name="update_profile"),
    path("address/", views.address, name="address"),
    path("add-address/", views.add_address, name="add_address"),
    path("delete_address/<int:id>/", views.delete_address, name="delete_address"),
    path("update_address/<int:id>/", views.update_address, name="update_address"),
    path("order-track/", views.order_track, name="order-track"),
    path(
        "cancel-product/<int:id>/<int:oid>/",
        views.cancel_product,
        name="cancel_product",
    ),
    path("cancel-order/<int:id>/", views.cancel_order, name="cancel_order"),
    path("remove-order/<int:id>/", views.remove_order, name="remove_order"),
    path("rewards/", views.rewards, name="rewards"),
    path("wallet/", views.wallet, name="wallet"),
    path("return-page/<int:id>/", views.return_page, name="return_page"),
    path("return-order/<int:id>/", views.return_order, name="return_order"),
    path("return-orders/", views.returnorder_page, name="returned_page"),
    path("view-returns/<int:id>/", views.view_returns, name="view_returns"),
    path("approve-return/<int:id>/", views.approve_return, name="approve_return"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("add-to-wishlist/<int:id>/", views.add_wishlist, name="add_wishlist"),
    path("remove-wishlist/<int:id>/", views.remove_wishlist, name="remove_wishlist"),
]

orders/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from .models import *

class FormWithCaptcha(forms.Form):
    captcha = ReCaptchaField()



class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['review','rating']

        

orders/views.py
import datetime
import json

from cart.models import *
from cart.views import _cart_id
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import never_cache
from user_profile.models import *

from .forms import FormWithCaptcha
from .models import *
from .forms import *


# Create your views here.
@never_cache
@login_required(login_url="userauth:login")
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        address = Address.objects.filter(user=request.user)
        profile = User_profile.objects.get(user=request.user)
    except:
        address = None
        profile = None
        messages.warning(request, 'Please complete your profile to proceed.')
        return redirect('user_profile:profile')

    cart_item = Cartitem.objects.filter(user=request.user)
    all_cart_item = not any(item.product.stock <= 0 for item in cart_item)

    if not all_cart_item:
        messages.error(request, 'One of the selected items is out of stock.')
        return redirect("cart:cart")

    try:
        tax = 0
        grand_total = 0
        shipping = 0

        cart_items = Cartitem.objects.filter(user=request.user, is_active=True)

        if not cart_items.exists():
            return redirect("main:shop")

        for cart_item in cart_items:
            product_price = cart_item.product.price
            product_offer = cart_item.product.offer
            category_offer = cart_item.product.category.offer
            
            if product_offer is None and category_offer is None:
                total += product_price * cart_item.quantity
                quantity += cart_item.quantity
            else:
                if product_offer and category_offer:
                    discount = max(product_offer.discount, category_offer.discount)
                elif product_offer:
                    discount = product_offer.discount
                else:
                    discount = category_offer.discount
                
                discount_price = (discount / 100) * float(product_price)
                discount_amount = float(product_price) - discount_price
                total += discount_amount * cart_item.quantity
                quantity += cart_item.quantity

        tax = (2 * total) / 100
        shipping = 20
        grand_total = total + shipping + tax

    except ObjectDoesNotExist:
        pass

    context = {
        "total": total,
        "quantity": quantity,
        "cart_items": cart_items,
        "captcha": FormWithCaptcha,
        "tax": tax,
        "shipping": shipping,
        "grandtotal": grand_total,
        "address": address,
        "profile": profile,
    }

    return render(request, "order/checkout.html", context)


@never_cache
@login_required(login_url="userauth:login")
def place_order(request, total=0, quantity=0):
    try:
        current_user = request.user
        cart_items = Cartitem.objects.filter(user=current_user)
        cart_count = cart_items.count()

        if request.method == "POST":
            selected_address_id = request.POST.get("address")
            payment_method = request.POST.get("pay-method")
            captcha = request.POST.get("g-recaptcha-response")

            if not selected_address_id:
                messages.error(request,"Please add an address from your profile to proceed")
                return redirect("orders:checkout")

            if not captcha:
                messages.error(request, "Confirm you are not a Robot")
                return redirect("orders:checkout")

            if payment_method == "COD":
                selected_address = get_object_or_404(
                    Address, id=selected_address_id, user=current_user
                )
                profile = User_profile.objects.get(user=current_user)

                tax = 0
                grand_total = 0
                shipping = 20  # Fixed shipping cost

                for cart_item in cart_items:
                    product_price = cart_item.product.price
                    product_offer = cart_item.product.offer
                    category_offer = cart_item.product.category.offer
                    
                    if product_offer is  None and category_offer is None:
                        total += cart_item.product.price * cart_item.quantity
                        quantity += cart_item.quantity
                    else:
                        if product_offer and category_offer:
                            discount = max(product_offer.discount,category_offer.discount)
                        elif product_offer:
                            discount = product_offer.discount
                        else:
                            discount = category_offer.discount
                        discount_price = (discount / 100) * float(product_price)
                        discount_amount = float(product_price) - discount_price
                        total += discount_amount * cart_item.quantity
                        quantity += cart_item.quantity

                tax = (2 * total) / 100
                grand_total = total + shipping + tax

                if 'disc_total' in request.session:
                    grand_total = request.session['disc_total']
                    del request.session['disc_total']

                data = Order(
                    user=current_user,
                    payment=payment_method,
                    first_name=profile.first_name,
                    last_name=profile.last_name,
                    phone=profile.mobile_number,
                    phone2=selected_address.phone,
                    email=profile.user.email,
                    address_line_1=selected_address.address,
                    state=profile.state,
                    district=selected_address.district,
                    zipcode=selected_address.zipcode,
                    hometown=selected_address.hometown,
                    order_total=grand_total,
                    tax=tax,
                    ip=request.META.get("REMOTE_ADDR"),
                    is_ordered=True,
                )

                data.save()

                if payment_method == "COD":
                    data.payment_status = "Pending"

                yr = int(datetime.date.today().strftime("%Y"))
                dt = int(datetime.date.today().strftime("%d"))
                mt = int(datetime.date.today().strftime("%m"))
                d = datetime.date(yr, mt, dt)
                current_date = d.strftime("%Y%m%d")
                order_number = current_date + str(data.id)
                data.order_number = order_number
                data.save()

                cart_items = Cartitem.objects.filter(user=request.user)
                for item in cart_items:
                    orderproduct = OrderProduct(
                        order=data,
                        payment=payment_method,
                        user=request.user,
                        product=item.product,
                        quantity=item.quantity,
                        product_price=item.product.price,
                        ordered=True,
                    )

                    orderproduct.save()

                    product = item.product
                    product.stock -= item.quantity
                    product.save()

                Cartitem.objects.filter(user=request.user).delete()

                if cart_count <= 0:
                    print(cart_count)
                    return redirect("main:shop")

                return render(request, "order/thankyou.html")
            
            elif payment_method == 'wallet':
                wallet = Wallet.objects.get(user=current_user)
                selected_address = get_object_or_404(
                    Address, id=selected_address_id, user=current_user
                )
                profile = User_profile.objects.get(user=current_user)

                tax = 0
                grand_total = 0
                shipping = 20  # Fixed shipping cost

                for cart_item in cart_items:
                    product_price = cart_item.product.price
                    product_offer = cart_item.product.offer
                    category_offer = cart_item.product.category.offer
                    
                    if product_offer is  None and category_offer is None:
                        total += cart_item.product.price * cart_item.quantity
                        quantity += cart_item.quantity
                    else:
                        if product_offer and category_offer:
                            discount = max(product_offer.discount,category_offer.discount)
                        elif product_offer:
                            discount = product_offer.discount
                        else:
                            discount = category_offer.discount
                        discount_price = (discount / 100) * float(product_price)
                        discount_amount = float(product_price) - discount_price
                        total += discount_amount * cart_item.quantity
                        quantity += cart_item.quantity


                tax = (2 * total) / 100
                grand_total = total + shipping + tax

                if 'disc_total' in request.session:
                    grand_total = request.session['disc_total']
                    del request.session['disc_total']

                if wallet.wallet < grand_total:
                    messages.error(request, "Insufficient funds in the wallet.")
                    return redirect("orders:checkout")
                
                wallet.wallet -= grand_total
                wallet.save()

templates/order/list_orders.html
{% extends "admin/adminbase.html" %}
{% load static %}

{% block body %}
<style>
  @import url("https://fonts.googleapis.com/css2?family=Poppins:weight@100;200;300;400;500;600;700;800&display=swap");


  body{
   background-color:#eee;
   font-family: "Poppins", sans-serif;
   font-weight: 300;
  }

  .height{
   height: 12vh;
  }
  

  .search{
  position: relative;
  box-shadow: 0 0 40px rgba(51, 51, 51, .1);
  right:14px;
    
  }

  .search input{

   height: 45px;
   text-indent: 25px;
   border: 2px solid #d6d4d4;


  }


  .search input:focus{

   box-shadow: none;
   border: 2px solid blue;


  }

  .search .fa-search{

   position: absolute;
   top: 20px;
   left: 16px;

  }

  .search button{

   position: absolute;
   top: 1px;
   right: 1px;
   height: 43px;
   width: 112px;
   background: blue;
   border-radius: 0;

  }

  .status-dropdown {
    width: 150px; /* Adjust the width as needed */
    background-color: #d1ecf1; /* Default background color */
}

.status-dropdown option[value="New"] {
    background-color: #cce5ff; /* Custom background color for 'New' status */
}

.status-dropdown option[value="Accepted"] {
    background-color: #d4edda; /* Custom background color for 'Accepted' status */
}

.status-dropdown option[value="Completed"] {
    background-color: #d1e7dd; /* Custom background color for 'Completed' status */
}

.status-dropdown option[value="Cancelled"] {
    background-color: #f8d7da; /* Custom background color for 'Cancelled' status */
}

</style>


        <div class="card-body">
            <h4 class="card-title">Manage Your Orders</h4>
            <br>
            
            <br>
            <br>
            {% for message in messages  %}
            <h6 class="text text-success">{{message}}</h6>
            {% endfor %}
            <br>
            <div class="container">

              <div class="row height d-flex justify-content-start align-items-center">
        
                <div class="col-md-8">
        
                  <div class="search">
                    <i class="fa fa-search"></i>
                    <form method="get" action=''>
                      {% csrf_token %}
                    <input type="text" class="form-control" name="search" placeholder="Search users here">
                    <button class="btn btn-primary">Search</button>
                    </form>
                  </div>
                  
                </div>
                
              </div>
          </div>
            
          <div class="row">
            <div class="col-12">
              <div class="table-responsive">
                <table  class="display expandable-table" style="width:100%">
                  <thead>
                    <tr>
                      <th>Id</th>
                      <th>User</th>
                      <th>email</th>
                      <th>State</th>
                      <th>District</th>
                      <th>View more</th>
                      <th>Order Status</th>
                      <th>Payment status</th>
                      <th>Edit status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for order in orders  %}
                    <tr>
                      {% if order.status == 'Cancel' %}
                      <td><s style ="color:red;">#{{order.order_number}}</s></td>
                      <td><s style ="color:red;">{{order.user.username}}</s></td>
                      <td><s style ="color:red;">{{order.email}}</s></td>
                      <td><s style ="color:red;">{{order.state}}</s></td>
                      <td><s style ="color:red;">{{order.district}}</s></td>
                      <td><a href='{% url "orders:view_order" order.id %}' class="btn btn-outline-info btn-sm">view</a></td>
                      <td style = "color:red;">{{order.status}}</td>
                      <td style = "color:red;">{{order.payment_status}}</td>
                      <td ><a href="" data-bs-toggle="modal" data-bs-target="#addEmployeeModal-{{forloop.counter}}" class="btn btn-warning btn-sm" >Edit</a></td>
                     
                      {% elif order.payment_status == 'Completed' and order.status == 'Deliverd' %}
                      <td style="color:green;">#{{order.order_number}}</td>
                      <td style="color:green;">{{order.user.username}}</td>
                      <td style="color:green;">{{order.email}}</td>
                      <td style="color:green;">{{order.state}}</td>
                      <td style="color:green;">{{order.district}}</td>
                      <td><a href='{% url "orders:view_order" order.id %}' class="btn btn-outline-info btn-sm">view</a></td>
                      <td style="color:green;">{{order.status}}</td>
                      <td style="color:green;">{{order.payment_status}}</td>
                      <td><a href="" data-bs-toggle="modal" data-bs-target="#addEmployeeModal-{{forloop.counter}}" class="btn btn-warning btn-sm" >Edit</a></td>
                      
                      {% elif order.status == 'Return' %}
                      <td style="color:blue;">#{{order.order_number}}</td>
                      <td style="color:blue;">{{order.user.username}}</td>
                      <td style="color:blue;">{{order.email}}</td>
                      <td style="color:blue;">{{order.state}}</td>
                      <td style="color:blue;">{{order.district}}</td>
                      <td><a href='{% url "orders:view_order" order.id %}' class="btn btn-outline-info btn-sm">view</a></td>
                      <td style="color:blue;">{{order.status}}</td>
                      <td style="color:blue;">{{order.payment_status}}</td>
                      <td><a href="" data-bs-toggle="modal" data-bs-target="#addEmployeeModal-{{forloop.counter}}" class="btn btn-warning btn-sm" >Edit</a></td>

                      {% else %}
                      <td>#{{order.order_number}}</td>
                      <td>{{order.user.username}}</td>
                      <td>{{order.email}}</td>
                      <td>{{order.state}}</td>
                      <td>{{order.district}}</td>
                      <td><a href='{% url "orders:view_order" order.id %}' class="btn btn-outline-info btn-sm">view</a></td>
                      <td>{{order.status}}</td>
                      <td>{{order.payment_status}}</td>
                      <td><a href="" data-bs-toggle="modal" data-bs-target="#addEmployeeModal-{{forloop.counter}}" class="btn btn-warning btn-sm" >Edit</a></td>
                      
                      {% endif %}
                    </tr>
                    {% endfor %}
                  </tbody>
              </table>
              </div>
            </div>
        
            {% for order in orders   %}
                    <div id="addEmployeeModal-{{forloop.counter}}" class="modal fade">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <form action='{% url "orders:change_status" order.id %}' method="post" >
                                {% csrf_token %}
                                    <div class="modal-header">						
                                        <h4 class="modal-title">Edit Status</h4>
                                        
                                    </div>
                    
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label>Payment status</label>
                                            
                                            
                                                <select class="form-select status-dropdown" name="payment-status" >
                                                    <option value="Pending" {% if order.payment_status == 'New' %}selected{% endif %}>Pending</option>
                                                    <option value="Completed" {% if order.payment_status == 'Completed' %}selected{% endif %}>Completed</option>
                                                    
                                                </select>
                                        </div>
                    
                                        <div class="form-group">
                                            <label>Order status</label>
                                            

                                                <select class="form-select status-dropdown" name="order-status" id="orderStatus">
                                                    {% for choice in order_status_choices %}
                                                    <option value="{{ choice.0 }}" {% if choice.0 == order.status %}selected{% endif %}>
                                                        {{ choice.1 }}
                                                    </option>
                                                {% endfor %}
                                                </select>
                                            
                                            
                                        </div>
                                        <div style="margin-bottom: 50px;">
                                          <a href="{% url "orders:soft_remove" order.id %}" class="btn btn-warning btn-sm">Remove</a>
                                          <a href="{% url "orders:order_delete" order.id %}" class="btn btn-danger btn-sm">Delete</a>
                                           
                                      </div>

                                        <div class="modal-footer">
                                            <input type="button" class="btn btn-danger" data-dismiss="modal" value="Cancel">
                                            <input type="submit" class="btn btn-success" value="Save changes"> 
                                             
                                        </div>

                                    </div>
                                    
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
             

{% endblock body %}

templates/order/thankyou.html
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link href='https://fonts.googleapis.com/css?family=Lato:300,400|Montserrat:700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
	<style>
		@import url(//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css);
		@import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);
        @import url(https://fonts.googleapis.com/css?family=Open+Sans:300);

.inner {
  position: absolute; 
  margin: auto; 
  width: 50px; 
  height: 95px; 
  top: 0px; 
  left: 0px; 
  bottom: 0px; 
  right: 0px; 
}

.inner > div {
  width: 50px; 
  height: 50px; 
  background-color: rgba(255, 255, 255, 0.7); 
  border-radius: 100%; 
  position: absolute; 
  transition: all 0.5s ease; 
}

.inner > div:first-child {
  margin-left: -27px; 
  animation: one 1.5s linear 1; 
}

.inner > div:nth-child(2) {
  margin-left: 27px; 
  animation: two 1.5s linear 1; 
}

.inner > div:nth-child(3) {
	margin-top: 54px; 
  margin-left: -27px; 
  animation: four 1.5s linear 1; 
}

.inner > div:nth-child(4) {
	margin-top: 54px; 
  margin-left: 27px; 
  animation: three 1.5s linear 1; 
}

@keyframes one {
  0% {
    transform: scale(1);
  }
  25% {
  	transform: scale(0.3);
  }
  50% {
    transform: scale(1);
  }
  75% {
    transform: scale(1.4);
  }
  100% {
    transform: scale(1);
  }
}

@keyframes two {
  0% {
    transform: scale(1.4);
  }
  25% {
  	transform: scale(1);
  }
  50% {
    transform: scale(0.3);
  }
  75% {
    transform: scale(1);
  }
  100% {
    transform: scale(1.4);
  }
}

@keyframes three {
  0% {
    transform: scale(1);
  }
  25% {
  	transform: scale(1.4);
  }
  50% {
    transform: scale(1);
  }
  75% {
    transform: scale(0.3);
  }
  100% {
    transform: scale(1);
  }
}

@keyframes four {
  0% {
    transform: scale(0.3);
  }
  25% {
  	transform: scale(1);
  }
  50% {
    transform: scale(1.4);
  }
  75% {
    transform: scale(1);
  }
  100% {
    transform: scale(0.3);
  }
}

.inner > div.done {
  margin-left: 0px; 
  margin-top:  27px; 
}

.inner > div.page {
  transform: scale(40); 
}

.pageLoad {
  position: fixed;  
  top: 0px; 
  left: 0px;  
  width: 100%; 
  height: 100vh; 
  background-color: #0A0A0A; 
  transition: all 0.3s ease; 
  z-index: 2; 
}

.pageLoad.off {
  opacity: 0; 
  pointer-events: none; 
}

button{
  border: none;
  background-color: #99ed99;
  width: 211px;
  height: 64px;
  border-radius: 34px;
  margin-top: 65px;
}

a{
    color: black !important;
    text-decoration: none;
    font-size: 20px;
}



	</style>
	<link rel="stylesheet" href="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/default_thank_you.css">
	<script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/jquery-1.9.1.min.js"></script>
	<script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/html5shiv.js"></script>
</head>
<body>
  <div class="pageLoad">
<div class="inner">
	<div></div>
  <div></div> 
  <div></div>
  <div></div>
</div> 
</div>
	<header class="site-header" id="header">
		<h1 class="site-header__title" data-lead-id="site-header-title">THANK YOU!</h1>
	</header>

	<div class="main-content">
		<i class="fa fa-check main-content__checkmark" id="checkmark"></i>
		<p class="main-content__body" data-lead-id="main-content-body">
            Thank you for your order! Your order is being processed and will be completed within 3-6 hours. You will receive an email confirmation when your order is completed.
        </p>
    <button><a  href="{% url "user_profile:order-track" %}">Track order</a></button>
	</div>

	<footer class="site-footer" id="footer">
		<p class="site-footer__fineprint" id="fineprint">Copyright ©2014 | All Rights Reserved</p>
	</footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        setTimeout(function() {
            $('.inner div').addClass('done'); 
            
            setTimeout(function() {
              $('.inner div').addClass('page'); 
              
              setTimeout(function() {
                  $('.pageLoad').addClass('off'); 
                
                $('body, html').addClass('on'); 
                
                
                }, 500)
            }, 500)
          }, 1500)
    </script>
</body>
</html>